config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :grandmas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grandma.rb
class Grandma < ApplicationRecord
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :grandma
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grandmas_controller.rb
class GrandmasController < ApplicationController
  before_action :set_grandma, only: [:show, :edit, :update, :destroy]

  # GET /grandmas
  # GET /grandmas.json
  def index
    @grandmas = Grandma.all
  end

  # GET /grandmas/1
  # GET /grandmas/1.json
  def show
  end

  # GET /grandmas/new
  def new
    @grandma = Grandma.new
  end

  # GET /grandmas/1/edit
  def edit
  end

  # POST /grandmas
  # POST /grandmas.json
  def create
    @grandma = Grandma.new(grandma_params)

    respond_to do |format|
      if @grandma.save
        format.html { redirect_to @grandma, notice: 'Grandma was successfully created.' }
        format.json { render :show, status: :created, location: @grandma }
      else
        format.html { render :new }
        format.json { render json: @grandma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grandmas/1
  # PATCH/PUT /grandmas/1.json
  def update
    respond_to do |format|
      if @grandma.update(grandma_params)
        format.html { redirect_to @grandma, notice: 'Grandma was successfully updated.' }
        format.json { render :show, status: :ok, location: @grandma }
      else
        format.html { render :edit }
        format.json { render json: @grandma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grandmas/1
  # DELETE /grandmas/1.json
  def destroy
    @grandma.destroy
    respond_to do |format|
      format.html { redirect_to grandmas_url, notice: 'Grandma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grandma
      @grandma = Grandma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grandma_params
      params.require(:grandma).permit(:name, :username, :password, :profile_img)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    @image = Image.create(image_params)
  end

  private
  def image_params
    params.require(:image).permit(:url, :grandma_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grandmas_helper.rb
module GrandmasHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/grandmas/_form.html.erb
<%= form_with(model: grandma, local: true) do |form| %>
  <% if grandma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grandma.errors.count, "error") %> prohibited this grandma from being saved:</h2>

      <ul>
      <% grandma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grandmas/edit.html.erb
<h1>Editing Grandma</h1>

<%= render 'form', grandma: @grandma %>

<%= link_to 'Show', @grandma %> |
<%= link_to 'Back', grandmas_path %>

app/views/grandmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grandmas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grandmas.each do |grandma| %>
      <tr>
        <td><%= grandma.name %></td>
        <td><%= grandma.username %></td>
        <td><%= grandma.password %></td>
        <td><%= link_to 'Show', grandma %></td>
        <td><%= link_to 'Edit', edit_grandma_path(grandma) %></td>
        <td><%= link_to 'Destroy', grandma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grandma', new_grandma_path %>

app/views/grandmas/new.html.erb
<h1>New Grandma</h1>

<%= render 'form', grandma: @grandma %>

<%= link_to 'Back', grandmas_path %>

app/views/grandmas/show.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="logo_title">
    <img id="insta_logo" src="https://cdn3.iconfinder.com/data/icons/transparent-on-dark-grey/500/icon-04-512.png" alt="logo">
    <p id="instagrandma_title"> Instagrandma </p>
  </div>
  <button type="button" name="button"> Log Out</button>
</nav>

<section>

  <img id="profile_img" src=" <%= @grandma.profile_img %> " alt="profile_img">
  <div class="user_info">
    <div>
    <span id="grandma_username"><%= @grandma.username %></span>
    <button type="button" name="button">Follow</button>
    </div>
    <%= @grandma.bio %>

  </div>
</section>
<p>
  <div class="images">
    <% @grandma.images.each do |image|%>
      <img class="insta_images" src="<%= image.url %>">
    <% end %>
  </div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script&display=swap" rel="stylesheet">
    <title>Instagrandma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>